### ISSUE TITLE
Request for support of DPT_FlowRate

### ISSUE THREAD

**Issue by marcschmiedchen** [marcschmiedchen/wolf_ism8#1]
I implemented DPT_FlowRate experimentally without testing (since I have no access to real network-traffic with this datapoint, I cannot test it).

When anyone reports back that it's working: that would be nice.

**Comment by nanosonde** [comment]
@marcschmiedchen

The flowrate is now shown. The value is correct, but the unit of measurement is wrong.
Home Assistant shows "ccm/h". This is wrong. It is supposed to be "m3/h".

**Comment by nanosonde** [comment]
See PR https://github.com/marcschmiedchen/wolf_ism8/pull/2 .

**Comment by marcschmiedchen** [comment]
Published on Pypi. Upgrade Library to 1.6, using:

python3 -m pip install --upgrade wolf-ism8
