### ISSUE TITLE
Keine Sensorwerte von ISM Modul8

### ISSUE THREAD

**Issue by stephangeiger1** [marcschmiedchen/wolf_ism8#3]
Hallo marcschmiedchen,

ich bekomme leider nur sehr wenig Werte vom ISM8 Modul zurückgeliefert. (Status Heizkreispumpe, Status  Solarpumpe, WarmwasserSolltemperatur)
Die Software läuft nun schon seit geraumer Zeit im HomeAssistant und es fehlen leider alle wirklich relevanten Werte. (WarmwasserIstTemperatur, StatusBrenner, Anlagendruck,... im groben ganzen so ziemlich alle Sensorwerte.)
Ich habe das ISM8i an einer Luft-Wärmepumpe BWL1S07 hängen.
Deine Software habe ich heute upgedatet.

Meine config.yaml sieht wie folgt aus:

wolf:
   devices: 
     - HG1
     - MM1
     - BM1
     - SM

Ich würde mich sehr über Support freuen.

Vielen Dank vorab!

Gruß Stephan

**Comment by marcschmiedchen** [comment]
Sorry für die späte Antwort! 
Wie Du schon selbst rausgefunden hast, ist die Konfigurationseinstellung für die Luftwärmepumpe "BWL". Das hatte ich derzeit in der Anleitung vergessen, bzw. weggelassen weil ich gar nicht wusste, was sich hinter "BWL" verbirgt.

Ist aber keine Issue der Bibliothek, sondern der Home-Assistant Config. Habs in der Anleitung ergänzt, danke.
