### ISSUE TITLE
Frage zu Werten der Fachmannebene

### ISSUE THREAD

**Issue by LilderoyGockhart** [marcschmiedchen/wolf_ism8#5]
Hallo,

erstmal danke für deine tolle Vorarbeit.
Ich überlege gerade wie ich das ISM8 in mein Homeassistant integriert bekommen und bin auf deine Integration gestoßen.

Mit stellt sich allerdings noch eine wichtige Frage:

Bekommt man mit dem ISM8i auch die Werte der Fachmannebene ausgegeben?

Danke und liebe Grüße

**Comment by stephangeiger1** [comment]
Hallo,
in der Montage und Bedienungsanleitung ist eine Tabelle mit allen Datenpunkten auf die mit dem ISM8 zugegriffen werden kann.
Fachmannparameter können nicht über das ISM8 eingestellt werden.


Gruß Stephan

**Comment by marcschmiedchen** [comment]
Hallo, 
wie Stephan bereits geschrieben hat, kann man keine Fachmann-Parameter setzen. Alle zugänglichen Werte kann man entweder in der Datei "ism8_constants.py" relativ leicht herauslesen, oder in der aktuellen Doku von Wolf. Ich hab die mal in der Beschreibung des Repo verlinkt, aber ich weiss nicht, wie lange der Link gültig bleibt. Ist ein CDN anscheinend. Ich möchte die PDF nicht hier anbieten, um Ärger vorzubeugen. Aber im Zweifel hilft auch immer Google.
